server:
  port: 9090
management:
  context-path: /manage
  security:
    enabled: false
endpoints:
  enabled: true
  env:
    enabled: true
  health:
    enabled: true
    sensitive: false
  mappings:
    enabled: true
summer:
  jolt:
    devMode: true
  xslt:
    devMode: true
  health:
    status: KO
    use_http_status: false
  operation_logging:
    log_requests: true
    included_packages: org.greeneyed.demo        