server:
  port: 9090
spring:
  config:
    use-legacy-processing: true
management:
   endpoints:
      web:
         base-path: /manage
         exposure:
            include: health,info,env,mappings,refresh,loggers,configInspector,configprops,actuators
summer:
  jolt:
    devMode: true
  xslt:
    devMode: true
    parameterPreffix: x_
  health:
    status: KO
    use_http_status: false
  operation_logging:
    log_requests: true
    included_packages: org.greeneyed.demo        