server:
  port: 9090
management:
  context-path: /manage
  security:
    enabled: false
management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: health,info,env,mappings,loggers,configInspector,configprops,actuatorsmanagement
summer:
  jolt:
    devMode: true
  xslt:
    devMode: true
  health:
    status: KO
    use_http_status: false
  operation_logging:
    log_requests: true
    included_packages: org.greeneyed.demo        